# Generated by Django 4.0.4 on 2022-04-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('serum', models.FloatField()),
                ('sg', models.FloatField()),
                ('rbc', models.IntegerField()),
                ('pc', models.IntegerField()),
                ('pcc', models.IntegerField()),
                ('ba', models.IntegerField()),
                ('bgr', models.IntegerField()),
                ('bu', models.IntegerField()),
                ('pot', models.FloatField()),
                ('pcv', models.IntegerField()),
                ('wbcc', models.IntegerField()),
                ('rbcc', models.FloatField()),
                ('htn', models.IntegerField()),
                ('dm', models.IntegerField()),
                ('cad', models.IntegerField()),
                ('pe', models.IntegerField()),
                ('ane', models.IntegerField()),
                ('yclass', models.CharField(max_length=6)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
