# Generated by Django 4.0.4 on 2022-04-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='weight',
            field=models.FloatField(default=40),
            preserve_default=False,
        ),
    ]
